---
title: "Cleaning clinical data"
date: 25-02-2025
format: 
  html:
    toc: true
    toc-location: left
---

```{r}
#| label: setup
#| include: false

lst.packages <- c("here","ggplot2","gtsummary","gt","dplyr","viridis")

if (!require("pacman")) install.packages("pacman")
pacman::p_load(char = lst.packages)

# Read environment file
readRenviron(here("config.env"))

datadir <- Sys.getenv("datadir")
resultsdir <- Sys.getenv("resultsdir")

# File paths
clinical.filename <- file.path(resultsdir, "clinical.txt")
pan.cancer.filename <- file.path(
  resultsdir,
  "TCGA-CDR-SupplementalTableS1.txt"
)
output.filename <- file.path(resultsdir, "clinical-clean.txt")

knitr::opts_chunk$set(fig.path = "figures/", warning = FALSE, message = FALSE)
```

## Data formatting

```{r}
#| label: files
#| echo: false

cat(
  "Data imported from extract-data.r:",
  "\n ", paste0("results/", basename(clinical.filename)),
  "\n ", paste0("results/", basename(pan.cancer.filename), "\n"),
  "Output cleaned saved to:",
  "\n ", paste0("results/", basename(output.filename)), "\n"
)
```

### Cleaning

```{r}
#| label: cleaning
#| 
# Format raw clinical data
raw <- readLines(clinical.filename)
raw <- strsplit(raw, "\t")
raw <- sapply(raw, function(sample) sample)
colnames(raw) <- raw[1, ]
raw <- raw[-1, ]
raw <- as.data.frame(raw, stringsAsFactors = F)

clinical <- data.frame(
  participant = sub("[^-]+-[^-]+-", "", raw$patient.bcr_patient_barcode),
  stringsAsFactors = F
)

clinical$participant <- toupper(clinical$participant)
clinical$female <- raw$patient.gender == "female"
clinical$histology <- raw$patient.tumor_samples.tumor_sample.tumor_histologies.tumor_histology.histological_type
clinical$age.at.diagnosis <- as.numeric(raw$patient.age_at_initial_pathologic_diagnosis)
clinical$estrogen.receptor.status <- raw$patient.breast_carcinoma_estrogen_receptor_status
clinical$progesterone.receptor.status <- raw$patient.breast_carcinoma_progesterone_receptor_status
clinical$her2.status <- raw$patient.lab_proc_her2_neu_immunohistochemistry_receptor_status
clinical$ethnicity <- raw$patient.ethnicity
clinical$race <- raw$patient.race_list.race
clinical$positive.lymphnodes <- as.numeric(raw$patient.number_of_lymphnodes_positive_by_he)
clinical$stage <- raw$patient.stage_event.pathologic_stage
clinical$tnm.m.category <- raw$patient.stage_event.tnm_categories.pathologic_categories.pathologic_m
clinical$tnm.n.category <- raw$patient.stage_event.tnm_categories.pathologic_categories.pathologic_n
clinical$tnm.t.category <- raw$patient.stage_event.tnm_categories.pathologic_categories.pathologic_t
clinical$lymphocyte.infiltration <- as.numeric(raw$patient.samples.sample.portions.portion.slides.slide.percent_lymphocyte_infiltration)
clinical$monocyte.infiltration <- as.numeric(raw$patient.samples.sample.portions.portion.slides.slide.percent_monocyte_infiltration)
clinical$neutrophil.infiltration <- as.numeric(raw$patient.samples.sample.portions.portion.slides.slide.percent_neutrophil_infiltration)
clinical$necrosis.percent <- as.numeric(raw$patient.samples.sample.portions.portion.slides.slide.percent_necrosis)
clinical$normal.cells.percent <- as.numeric(raw$patient.samples.sample.portions.portion.slides.slide.percent_normal_cells)
clinical$stromal.cells.percent <- as.numeric(raw$patient.samples.sample.portions.portion.slides.slide.percent_stromal_cells)
clinical$tumor.cells.percent <- as.numeric(raw$patient.samples.sample.portions.portion.slides.slide.percent_tumor_cells)

clinical$stage[clinical$stage == "stage x"] <- NA

clinical$tnm.m.category <- factor(
  as.character(clinical$tnm.m.category),
  levels = c("m0", "m1")
)

clinical$tnm.t.category[clinical$tnm.t.category == "tx"] <- NA
clinical$tnm.t.category[grepl("t1", clinical$tnm.t.category)] <- "t1"
clinical$tnm.t.category[grepl("t2", clinical$tnm.t.category)] <- "t2"
clinical$tnm.t.category[grepl("t3", clinical$tnm.t.category)] <- "t3"
clinical$tnm.t.category[grepl("t4", clinical$tnm.t.category)] <- "t4"

clinical$tnm.n.category[clinical$tnm.n.category == "nx"] <- NA
clinical$tnm.n.category[grepl("n0", clinical$tnm.n.category)] <- "n0"
clinical$tnm.n.category[grepl("n1", clinical$tnm.n.category)] <- "n1"
clinical$tnm.n.category[grepl("n2", clinical$tnm.n.category)] <- "n2"
clinical$tnm.n.category[grepl("n3", clinical$tnm.n.category)] <- "n3"

clinical.pan <- read.table(pan.cancer.filename, header = T, sep = "\t", stringsAsFactors = F)
clinical.pan <- clinical.pan[which(clinical.pan$type == "HNSC"), ]
clinical.pan$participant <- sub("[^-]+-[^-]+-", "", clinical.pan$bcr_patient_barcode)
clinical.pan <- clinical.pan[match(clinical$participant, clinical.pan$participant), ]
clinical$pfi <- clinical.pan$PFI
clinical$pfi.time <- clinical.pan$PFI.time
clinical$dfi <- clinical.pan$DFI
clinical$dfi.time <- clinical.pan$DFI.time
```

## Sample overview

### Patient metadata

```{r}
#| label: patients
#| fig-width: 12
#| fig-height: 4

# Age
p_age <- clinical.pan |>
  ggplot(aes(x = age_at_initial_pathologic_diagnosis)) +
  geom_histogram(binwidth = 2) +
  theme_minimal() +
  labs(x = "Age at diagnosis")

# Sex
p_sex <- clinical.pan |>
  ggplot(aes(x = gender, y = age_at_initial_pathologic_diagnosis)) +
  geom_boxplot(fill = "grey") +
  theme_minimal() +
  labs(y = "Age at diagnosis", x = "")

# Tumour grade
p_grade <- clinical.pan |> 
  group_by(histological_grade, clinical_stage) |> 
  summarise(count = n()) |>
  filter(!histological_grade == "[Not Available]",
         !clinical_stage == "[Not Available]") |>
  ggplot(aes(x = clinical_stage, y = count, fill = histological_grade)) +
    geom_bar(position = "fill", stat = "identity") +
    scale_fill_viridis(discrete = TRUE, name = "Histological grade") +
  theme_minimal() +
  theme(legend.position = "bottom") +
  labs(x = "Clinical stage", y = "")

gridExtra::grid.arrange(p_age, p_sex, p_grade, nrow = 1, widths = c(0.4,0.2,0.4))

```

### Tumor characteristics

```{r}
#| label: cells
#| fig-width: 10
#| fig-height: 5

# Cell parameters
cell_params <- grep("infiltration|cells.percent", names(clinical), value = T)

# Plot distribution
p_cells <- lapply(cell_params, function(param){
  clinical |>
    ggplot(aes(x = .data[[param]])) +
    geom_density() +
    theme_minimal()
})

gridExtra::grid.arrange(grobs = p_cells, nrow = 2, top=grid::textGrob("Distribution of cellular parameters"))

```

## Cleaned output

```{r}
#| label: output data
#| warning: FALSE

gtsummary::tbl_summary(select(clinical, -participant),
                       missing = "no")

write.table(clinical, file = output.filename, row.names = F, col.names = T, sep = "\t")
```
